"""Init

Revision ID: 38126f1a62e6
Revises: 436d2f837620
Create Date: 2023-04-12 10:55:52.189023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38126f1a62e6'
down_revision = '436d2f837620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('contacts_email_key', 'contacts', type_='unique')
    op.drop_constraint('contacts_phone_key', 'contacts', type_='unique')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.create_unique_constraint('contacts_phone_key', 'contacts', ['phone'])
    op.create_unique_constraint('contacts_email_key', 'contacts', ['email'])
    op.drop_column('contacts', 'updated_at')
    # ### end Alembic commands ###
